export const actions = {
  blog: {
    DATA_FETCHING: "BLOG_DATA_FETCHING",
    DATA_FETCHED: "BLOG_DATA_FETCHED",
    DATA_FETCH_ERROR: "BLOG_DATA_FETCH_ERROR",
    DATA_CREATED: "BLOG_DATA_CREATED",
    DATA_EDITED: "BLOG_DATA_EDITED",
    BLOG_DELETED: "BLOG_DATA_DELETED",
    CURRENT_PAGE: "CURRENT_PAGE",
    LIKE: "LIKE",
  },
};
